name: BasePlugin
version: 2.7.1
main: fun.xd.suka.Main
description: Encoded by Blue Millennium
authors: [SukaXD, Suisuroru]

commands:
  kill:
    description: kill entities
    usage: /kill <entities>
  ban:
    description: Ban a player
    usage: /ban <player> <reason>
  pardon:
    description: Unban a player
    usage: /pardon <player>
  basepluginhelp:
    description: Baseplugin help
    usage: /basepluginhelp
    aliases: [ bphelp ]
  report:
    description: Report a player
    usage: /report <player> <reason>
    aliases: [ bprp ]
  bpreload:
    description: Reload config
    usage: /bpreload
    aliases: [ bprl ]
  bpconfig:
    description: Reload config
    usage: /bpconfig [reload|query|set] [args...]
    aliases: [ bpcfg ]
  query-report:
    description: Query reports
    usage: /query-report
    aliases: [ qr ]
  baseplugin:
    description: Baseplugin functions
    usage: /baseplugin [report|reload|query-report] [args...]
    aliases: [ bp ]