name: BasePlugin
version: 2.5.2
main: xd.suka.Main
description: BasePlugin
author: SukaXD, Suisuroru

commands:
  report:
    description: Report a player
    usage: /report <player> <reason>
    aliases: [r]
  bpreload:
    description: Reload config
    usage: /bpreload
    aliases: [bpr]
  query-report:
    description: Query reports
    usage: /query-report
    aliases: [qr]
  baseplugin:
    description: Baseplugin functions
    usage: /baseplugin [report|reload|query-report] [args...]
    aliases: [bp]