name: BasePlugin
version: 2.7.5
main: fun.blue_millennium.Main
description: Encoded by Blue Millennium
authors: [ SukaXD, Suisuroru ]

commands:
  kill:
    description: kill entities
    usage: /kill <entities>
  ban:
    description: Ban a player
    usage: /ban <player> <reason>
  pardon:
    description: Unban a player
    usage: /pardon <player>
  basepluginhelp:
    description: Baseplugin help
    usage: /basepluginhelp
    aliases: [ bphelp ]
  report:
    description: Report a player
    usage: /report <player> <reason>
    aliases: [ bprp ]
  bpreload:
    description: Reload config
    usage: /bpreload
    aliases: [ bprl ]
  bpconfig:
    description: config functions
    usage: /bpconfig [reload|query|set] [args...]
    aliases: [ bpcfg ]
  bpdata:
    description: data functions
    usage: /bpdata [query] [args...]
    aliases: [ bpd ]
  query-report:
    description: Query reports
    usage: /query-report
    aliases: [ qr ]
  rcon:
    description: rcon functions
    usage: /rcon ip:port psd command
  link:
    description: link account and qq
    usage: /link name qq
  baseplugin:
    description: Baseplugin functions
    usage: /baseplugin [help|data|report|reload|query-report] [args...]
    aliases: [ bp ]